//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Localized", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 最前頁 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_GoFirstPage {
            get {
                return ResourceManager.GetString("CTL_BTN_GoFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後頁 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_GoLastPage {
            get {
                return ResourceManager.GetString("CTL_BTN_GoLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下一頁 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_GoNextPage {
            get {
                return ResourceManager.GetString("CTL_BTN_GoNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上一頁 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_GoPreviousPage {
            get {
                return ResourceManager.GetString("CTL_BTN_GoPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中國信託平台信用卡繳款 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_中國信託平台信用卡繳款 {
            get {
                return ResourceManager.GetString("CTL_BTN_中國信託平台信用卡繳款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_修改 {
            get {
                return ResourceManager.GetString("CTL_BTN_修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_停用 {
            get {
                return ResourceManager.GetString("CTL_BTN_停用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_列印 {
            get {
                return ResourceManager.GetString("CTL_BTN_列印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_刪除 {
            get {
                return ResourceManager.GetString("CTL_BTN_刪除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_啟用 {
            get {
                return ResourceManager.GetString("CTL_BTN_啟用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回上一頁 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_回上一頁 {
            get {
                return ResourceManager.GetString("CTL_BTN_回上一頁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 土地銀行個人網路銀行繳款 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_土地銀行個人網路銀行繳款 {
            get {
                return ResourceManager.GetString("CTL_BTN_土地銀行個人網路銀行繳款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_新增 {
            get {
                return ResourceManager.GetString("CTL_BTN_新增", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_查詢 {
            get {
                return ResourceManager.GetString("CTL_BTN_查詢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生PDF憑單 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_產生PDF憑單 {
            get {
                return ResourceManager.GetString("CTL_BTN_產生PDF憑單", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生PDF收據 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_產生PDF收據 {
            get {
                return ResourceManager.GetString("CTL_BTN_產生PDF收據", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生PDF繳費單 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_產生PDF繳費單 {
            get {
                return ResourceManager.GetString("CTL_BTN_產生PDF繳費單", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生超商行動條碼 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_產生超商行動條碼 {
            get {
                return ResourceManager.GetString("CTL_BTN_產生超商行動條碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_確定 {
            get {
                return ResourceManager.GetString("CTL_BTN_確定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_確認 {
            get {
                return ResourceManager.GetString("CTL_BTN_確認", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網路ATM繳款 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_網路ATM繳款 {
            get {
                return ResourceManager.GetString("CTL_BTN_網路ATM繳款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_繳費 {
            get {
                return ResourceManager.GetString("CTL_BTN_繳費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複製 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_複製 {
            get {
                return ResourceManager.GetString("CTL_BTN_複製", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 財金平台信用卡繳款 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_財金平台信用卡繳款 {
            get {
                return ResourceManager.GetString("CTL_BTN_財金平台信用卡繳款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銀聯卡繳款 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_銀聯卡繳款 {
            get {
                return ResourceManager.GetString("CTL_BTN_銀聯卡繳款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離開 的當地語系化字串。
        /// </summary>
        internal static string CTL_BTN_離開 {
            get {
                return ResourceManager.GetString("CTL_BTN_離開", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定刪除此資料 的當地語系化字串。
        /// </summary>
        internal static string CTL_DeleteConfirm {
            get {
                return ResourceManager.GetString("CTL_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定停用此資料 的當地語系化字串。
        /// </summary>
        internal static string CTL_DisableConfirm {
            get {
                return ResourceManager.GetString("CTL_DisableConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定啟用此資料 的當地語系化字串。
        /// </summary>
        internal static string CTL_EnableConfirm {
            get {
                return ResourceManager.GetString("CTL_EnableConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;p&gt;營業時間：週一至週五  9:00至15:30 總行地址：10047臺北市中正區館前路46號   總行電話： 02-2348-3456  24小時服務電話：  客服中心:02-2314-6633    免費客訴電話：0800-231-590&lt;/p&gt;
        ///&lt;p&gt;COPYRIGHT© LANDBANK 版權所有:土地銀行 最佳瀏覽效果請使用 Internet Explorer7.0以上 1024x768 解析度&lt;/p&gt; 的當地語系化字串。
        /// </summary>
        internal static string CTL_Footer {
            get {
                return ResourceManager.GetString("CTL_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 共&lt;span&gt;{0}&lt;/span&gt;頁 的當地語系化字串。
        /// </summary>
        internal static string CTL_MaxPageNo {
            get {
                return ResourceManager.GetString("CTL_MaxPageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無維護權限 的當地語系化字串。
        /// </summary>
        internal static string CTL_NoMaintainAuth {
            get {
                return ResourceManager.GetString("CTL_NoMaintainAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不分頁 的當地語系化字串。
        /// </summary>
        internal static string CTL_NoPageSize {
            get {
                return ResourceManager.GetString("CTL_NoPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無查詢權限 的當地語系化字串。
        /// </summary>
        internal static string CTL_NoQueryAuth {
            get {
                return ResourceManager.GetString("CTL_NoQueryAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第&lt;span&gt;{0}&lt;/span&gt;頁 的當地語系化字串。
        /// </summary>
        internal static string CTL_PageNo {
            get {
                return ResourceManager.GetString("CTL_PageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提醒您～您已經6個月未更改密碼。 的當地語系化字串。
        /// </summary>
        internal static string CTL_RemindChangePWD1 {
            get {
                return ResourceManager.GetString("CTL_RemindChangePWD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 立即更改密碼 的當地語系化字串。
        /// </summary>
        internal static string CTL_RemindChangePWD2 {
            get {
                return ResourceManager.GetString("CTL_RemindChangePWD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代收學雜費服務網 的當地語系化字串。
        /// </summary>
        internal static string CTL_WebTitle {
            get {
                return ResourceManager.GetString("CTL_WebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;p&gt;歡迎光臨！&lt;/p&gt;&lt;p&gt;您已經成功登入代收學雜費服務網站。&lt;/p&gt; 的當地語系化字串。
        /// </summary>
        internal static string CTL_Welcome {
            get {
                return ResourceManager.GetString("CTL_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯徵KP3維護 的當地語系化字串。
        /// </summary>
        internal static string MENU_S6 {
            get {
                return ResourceManager.GetString("MENU_S6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 KP3資料登錄 的當地語系化字串。
        /// </summary>
        internal static string MENU_S6100001 {
            get {
                return ResourceManager.GetString("MENU_S6100001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 KP3預設值維護 的當地語系化字串。
        /// </summary>
        internal static string MENU_S6200001 {
            get {
                return ResourceManager.GetString("MENU_S6200001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 維護代碼檔 的當地語系化字串。
        /// </summary>
        internal static string MENU_維護代碼檔 {
            get {
                return ResourceManager.GetString("MENU_維護代碼檔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳 的當地語系化字串。
        /// </summary>
        internal static string 上傳 {
            get {
                return ResourceManager.GetString("上傳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳就學貸款金額 的當地語系化字串。
        /// </summary>
        internal static string 上傳就學貸款金額 {
            get {
                return ResourceManager.GetString("上傳就學貸款金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳批號 的當地語系化字串。
        /// </summary>
        internal static string 上傳批號 {
            get {
                return ResourceManager.GetString("上傳批號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳日期時間 的當地語系化字串。
        /// </summary>
        internal static string 上傳日期時間 {
            get {
                return ResourceManager.GetString("上傳日期時間", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳檔案格式 的當地語系化字串。
        /// </summary>
        internal static string 上傳檔案格式 {
            get {
                return ResourceManager.GetString("上傳檔案格式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳的可貸金額 的當地語系化字串。
        /// </summary>
        internal static string 上傳的可貸金額 {
            get {
                return ResourceManager.GetString("上傳的可貸金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上課時數 的當地語系化字串。
        /// </summary>
        internal static string 上課時數 {
            get {
                return ResourceManager.GetString("上課時數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 的當地語系化字串。
        /// </summary>
        internal static string 下載 {
            get {
                return ResourceManager.GetString("下載", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 ODS 的當地語系化字串。
        /// </summary>
        internal static string 下載ODS {
            get {
                return ResourceManager.GetString("下載ODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 XLS 的當地語系化字串。
        /// </summary>
        internal static string 下載XLS {
            get {
                return ResourceManager.GetString("下載XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 ODS 範本 的當地語系化字串。
        /// </summary>
        internal static string 下載範本ODS {
            get {
                return ResourceManager.GetString("下載範本ODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 XLS 範本 的當地語系化字串。
        /// </summary>
        internal static string 下載範本XLS {
            get {
                return ResourceManager.GetString("下載範本XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中文版 的當地語系化字串。
        /// </summary>
        internal static string 中文版 {
            get {
                return ResourceManager.GetString("中文版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代收日 的當地語系化字串。
        /// </summary>
        internal static string 代收日 {
            get {
                return ResourceManager.GetString("代收日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代收費用別資料不存在 的當地語系化字串。
        /// </summary>
        internal static string 代收費用別資料不存在 {
            get {
                return ResourceManager.GetString("代收費用別資料不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代收銀行/分行 的當地語系化字串。
        /// </summary>
        internal static string 代收銀行_分行 {
            get {
                return ResourceManager.GetString("代收銀行/分行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代收銀行/分行 的當地語系化字串。
        /// </summary>
        internal static string 代收銀行分行 {
            get {
                return ResourceManager.GetString("代收銀行分行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住址 的當地語系化字串。
        /// </summary>
        internal static string 住址 {
            get {
                return ResourceManager.GetString("住址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住宿代碼 的當地語系化字串。
        /// </summary>
        internal static string 住宿代碼 {
            get {
                return ResourceManager.GetString("住宿代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住宿名稱 的當地語系化字串。
        /// </summary>
        internal static string 住宿名稱 {
            get {
                return ResourceManager.GetString("住宿名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者密碼 的當地語系化字串。
        /// </summary>
        internal static string 使用者密碼_Mobile {
            get {
                return ResourceManager.GetString("使用者密碼_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者帳號 的當地語系化字串。
        /// </summary>
        internal static string 使用者帳號 {
            get {
                return ResourceManager.GetString("使用者帳號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 例如生日為2015年1月20日，請輸入20150120 的當地語系化字串。
        /// </summary>
        internal static string 例如生日為2015年1月20日請輸入20150120 {
            get {
                return ResourceManager.GetString("例如生日為2015年1月20日請輸入20150120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 便利商店收據請保留六個月 的當地語系化字串。
        /// </summary>
        internal static string 便利商店收據請保留六個月 {
            get {
                return ResourceManager.GetString("便利商店收據請保留六個月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 便利商店繳款（7-ELEVEN, 全家, 萊爾富, ＯＫ） 的當地語系化字串。
        /// </summary>
        internal static string 便利商店繳款 {
            get {
                return ResourceManager.GetString("便利商店繳款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string 備註 {
            get {
                return ResourceManager.GetString("備註", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 入帳日 的當地語系化字串。
        /// </summary>
        internal static string 入帳日 {
            get {
                return ResourceManager.GetString("入帳日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印收據 的當地語系化字串。
        /// </summary>
        internal static string 列印收據 {
            get {
                return ResourceManager.GetString("列印收據", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印繳費單 的當地語系化字串。
        /// </summary>
        internal static string 列印繳費單 {
            get {
                return ResourceManager.GetString("列印繳費單", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能 的當地語系化字串。
        /// </summary>
        internal static string 功能 {
            get {
                return ResourceManager.GetString("功能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string 功能名稱 {
            get {
                return ResourceManager.GetString("功能名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 助貸 的當地語系化字串。
        /// </summary>
        internal static string 助貸 {
            get {
                return ResourceManager.GetString("助貸", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出 ODS 的當地語系化字串。
        /// </summary>
        internal static string 匯出ODS {
            get {
                return ResourceManager.GetString("匯出ODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出 XLS 的當地語系化字串。
        /// </summary>
        internal static string 匯出XLS {
            get {
                return ResourceManager.GetString("匯出XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯款帳號 的當地語系化字串。
        /// </summary>
        internal static string 匯款帳號 {
            get {
                return ResourceManager.GetString("匯款帳號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯款銀行代碼 的當地語系化字串。
        /// </summary>
        internal static string 匯款銀行代碼 {
            get {
                return ResourceManager.GetString("匯款銀行代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 原就學貸款金額 的當地語系化字串。
        /// </summary>
        internal static string 原就學貸款金額 {
            get {
                return ResourceManager.GetString("原就學貸款金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可貸金額 的當地語系化字串。
        /// </summary>
        internal static string 可貸金額 {
            get {
                return ResourceManager.GetString("可貸金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合計項目 的當地語系化字串。
        /// </summary>
        internal static string 合計項目 {
            get {
                return ResourceManager.GetString("合計項目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商家代號 的當地語系化字串。
        /// </summary>
        internal static string 商家代號 {
            get {
                return ResourceManager.GetString("商家代號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用國際信用卡繳費 的當地語系化字串。
        /// </summary>
        internal static string 啟用國際信用卡繳費 {
            get {
                return ResourceManager.GetString("啟用國際信用卡繳費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 國際信用卡 的當地語系化字串。
        /// </summary>
        internal static string 國際信用卡 {
            get {
                return ResourceManager.GetString("國際信用卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 國際信用卡繳費 的當地語系化字串。
        /// </summary>
        internal static string 國際信用卡繳費 {
            get {
                return ResourceManager.GetString("國際信用卡繳費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖型驗證碼 的當地語系化字串。
        /// </summary>
        internal static string 圖型驗證碼 {
            get {
                return ResourceManager.GetString("圖型驗證碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖型驗證碼 的當地語系化字串。
        /// </summary>
        internal static string 圖型驗證碼_Mobile {
            get {
                return ResourceManager.GetString("圖型驗證碼_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ODS 報表 的當地語系化字串。
        /// </summary>
        internal static string 報表ODS {
            get {
                return ResourceManager.GetString("報表ODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 XLS 報表 的當地語系化字串。
        /// </summary>
        internal static string 報表XLS {
            get {
                return ResourceManager.GetString("報表XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (如要採用實體ATM、超商、臨櫃方式繳款，請點此按鈕) 的當地語系化字串。
        /// </summary>
        internal static string 如要採用實體ATM超商臨櫃方式繳款請點此按鈕 {
            get {
                return ResourceManager.GetString("如要採用實體ATM超商臨櫃方式繳款請點此按鈕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        internal static string 姓名 {
            get {
                return ResourceManager.GetString("姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學分基準 的當地語系化字串。
        /// </summary>
        internal static string 學分基準 {
            get {
                return ResourceManager.GetString("學分基準", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學分基準代碼 的當地語系化字串。
        /// </summary>
        internal static string 學分基準代碼 {
            get {
                return ResourceManager.GetString("學分基準代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學分基準(或課程)學分數 的當地語系化字串。
        /// </summary>
        internal static string 學分基準或課程學分數 {
            get {
                return ResourceManager.GetString("學分基準或課程學分數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學年 的當地語系化字串。
        /// </summary>
        internal static string 學年 {
            get {
                return ResourceManager.GetString("學年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學期 的當地語系化字串。
        /// </summary>
        internal static string 學期 {
            get {
                return ResourceManager.GetString("學期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學期代碼 的當地語系化字串。
        /// </summary>
        internal static string 學期代碼 {
            get {
                return ResourceManager.GetString("學期代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學期名稱 的當地語系化字串。
        /// </summary>
        internal static string 學期名稱 {
            get {
                return ResourceManager.GetString("學期名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學校 的當地語系化字串。
        /// </summary>
        internal static string 學校 {
            get {
                return ResourceManager.GetString("學校", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學　　　校 的當地語系化字串。
        /// </summary>
        internal static string 學校名稱_Mobile {
            get {
                return ResourceManager.GetString("學校名稱_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學校選擇有誤，請重新選擇學校 的當地語系化字串。
        /// </summary>
        internal static string 學校選擇有誤請重新選擇學校 {
            get {
                return ResourceManager.GetString("學校選擇有誤請重新選擇學校", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學生基本資料不存在 的當地語系化字串。
        /// </summary>
        internal static string 學生基本資料不存在 {
            get {
                return ResourceManager.GetString("學生基本資料不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學生專區登入 的當地語系化字串。
        /// </summary>
        internal static string 學生專區登入 {
            get {
                return ResourceManager.GetString("學生專區登入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學生登入 的當地語系化字串。
        /// </summary>
        internal static string 學生專區登入_Mobile {
            get {
                return ResourceManager.GetString("學生專區登入_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學生就貸 的當地語系化字串。
        /// </summary>
        internal static string 學生就貸 {
            get {
                return ResourceManager.GetString("學生就貸", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學生扣款轉帳銀行代碼 的當地語系化字串。
        /// </summary>
        internal static string 學生扣款轉帳銀行代碼 {
            get {
                return ResourceManager.GetString("學生扣款轉帳銀行代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學生扣款轉帳銀行帳號 的當地語系化字串。
        /// </summary>
        internal static string 學生扣款轉帳銀行帳號 {
            get {
                return ResourceManager.GetString("學生扣款轉帳銀行帳號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學生繳費資料不存在 的當地語系化字串。
        /// </summary>
        internal static string 學生繳費資料不存在 {
            get {
                return ResourceManager.GetString("學生繳費資料不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學號 的當地語系化字串。
        /// </summary>
        internal static string 學號 {
            get {
                return ResourceManager.GetString("學號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 學　　　號 的當地語系化字串。
        /// </summary>
        internal static string 學號_Mobile {
            get {
                return ResourceManager.GetString("學號_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 實際所修的學分 的當地語系化字串。
        /// </summary>
        internal static string 實際所修的學分 {
            get {
                return ResourceManager.GetString("實際所修的學分", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 對照表名稱 的當地語系化字串。
        /// </summary>
        internal static string 對照表名稱 {
            get {
                return ResourceManager.GetString("對照表名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 就學貸款可貸金額 的當地語系化字串。
        /// </summary>
        internal static string 就學貸款可貸金額 {
            get {
                return ResourceManager.GetString("就學貸款可貸金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 就貸代碼 的當地語系化字串。
        /// </summary>
        internal static string 就貸代碼 {
            get {
                return ResourceManager.GetString("就貸代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 就貸名稱 的當地語系化字串。
        /// </summary>
        internal static string 就貸名稱 {
            get {
                return ResourceManager.GetString("就貸名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 就貸金額項目 的當地語系化字串。
        /// </summary>
        internal static string 就貸金額項目 {
            get {
                return ResourceManager.GetString("就貸金額項目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已入帳 的當地語系化字串。
        /// </summary>
        internal static string 已入帳 {
            get {
                return ResourceManager.GetString("已入帳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已繳待銷 的當地語系化字串。
        /// </summary>
        internal static string 已繳待銷 {
            get {
                return ResourceManager.GetString("已繳待銷", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已繳款 的當地語系化字串。
        /// </summary>
        internal static string 已繳款 {
            get {
                return ResourceManager.GetString("已繳款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已過中信平台管道繳費期限。 的當地語系化字串。
        /// </summary>
        internal static string 已過中信平台管道繳費期限 {
            get {
                return ResourceManager.GetString("已過中信平台管道繳費期限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已過財金平台管道繳費期限。 的當地語系化字串。
        /// </summary>
        internal static string 已過財金平台管道繳費期限 {
            get {
                return ResourceManager.GetString("已過財金平台管道繳費期限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年級 的當地語系化字串。
        /// </summary>
        internal static string 年級 {
            get {
                return ResourceManager.GetString("年級", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 座號 的當地語系化字串。
        /// </summary>
        internal static string 座號 {
            get {
                return ResourceManager.GetString("座號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 批號 的當地語系化字串。
        /// </summary>
        internal static string 批號 {
            get {
                return ResourceManager.GetString("批號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支付寶繳費 的當地語系化字串。
        /// </summary>
        internal static string 支付寶繳費 {
            get {
                return ResourceManager.GetString("支付寶繳費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收入明細 的當地語系化字串。
        /// </summary>
        internal static string 收入明細 {
            get {
                return ResourceManager.GetString("收入明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收入科目 的當地語系化字串。
        /// </summary>
        internal static string 收入科目 {
            get {
                return ResourceManager.GetString("收入科目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收據 的當地語系化字串。
        /// </summary>
        internal static string 收據 {
            get {
                return ResourceManager.GetString("收據", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增╱查詢學生退費資料 的當地語系化字串。
        /// </summary>
        internal static string 新增查詢學生退費資料 {
            get {
                return ResourceManager.GetString("新增查詢學生退費資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string 明細 {
            get {
                return ResourceManager.GetString("明細", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後修改日期 的當地語系化字串。
        /// </summary>
        internal static string 最後修改日期 {
            get {
                return ResourceManager.GetString("最後修改日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未提供中信平台管道繳費。 的當地語系化字串。
        /// </summary>
        internal static string 未提供中信平台管道繳費 {
            get {
                return ResourceManager.GetString("未提供中信平台管道繳費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未提供財金平台管道繳費。  的當地語系化字串。
        /// </summary>
        internal static string 未提供財金平台管道繳費 {
            get {
                return ResourceManager.GetString("未提供財金平台管道繳費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未繳款 的當地語系化字串。
        /// </summary>
        internal static string 未繳款 {
            get {
                return ResourceManager.GetString("未繳款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未開放 的當地語系化字串。
        /// </summary>
        internal static string 未開放 {
            get {
                return ResourceManager.GetString("未開放", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無指定的繳款資料 的當地語系化字串。
        /// </summary>
        internal static string 查無指定的繳款資料 {
            get {
                return ResourceManager.GetString("查無指定的繳款資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        internal static string 查詢 {
            get {
                return ResourceManager.GetString("查詢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢繳款資料失敗 的當地語系化字串。
        /// </summary>
        internal static string 查詢繳款資料失敗 {
            get {
                return ResourceManager.GetString("查詢繳款資料失敗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 業務別碼 的當地語系化字串。
        /// </summary>
        internal static string 業務別碼 {
            get {
                return ResourceManager.GetString("業務別碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此繳費單未開放或是無效的繳費單 的當地語系化字串。
        /// </summary>
        internal static string 此繳費單未開放或是無效的繳費單 {
            get {
                return ResourceManager.GetString("此繳費單未開放或是無效的繳費單", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此繳費單限定使用『國際信用卡繳費』 的當地語系化字串。
        /// </summary>
        internal static string 此繳費單限定使用國際信用卡繳費 {
            get {
                return ResourceManager.GetString("此繳費單限定使用國際信用卡繳費", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每課程學分單價 的當地語系化字串。
        /// </summary>
        internal static string 每課程學分單價 {
            get {
                return ResourceManager.GetString("每課程學分單價", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 注意 的當地語系化字串。
        /// </summary>
        internal static string 注意 {
            get {
                return ResourceManager.GetString("注意", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 減免代碼 的當地語系化字串。
        /// </summary>
        internal static string 減免代碼 {
            get {
                return ResourceManager.GetString("減免代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 減免名稱 的當地語系化字串。
        /// </summary>
        internal static string 減免名稱 {
            get {
                return ResourceManager.GetString("減免名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 減免金額項目 的當地語系化字串。
        /// </summary>
        internal static string 減免金額項目 {
            get {
                return ResourceManager.GetString("減免金額項目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 減免類別代碼 的當地語系化字串。
        /// </summary>
        internal static string 減免類別代碼 {
            get {
                return ResourceManager.GetString("減免類別代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 減免類別名稱 的當地語系化字串。
        /// </summary>
        internal static string 減免類別名稱 {
            get {
                return ResourceManager.GetString("減免類別名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得登入者資訊 的當地語系化字串。
        /// </summary>
        internal static string 無法取得登入者資訊 {
            get {
                return ResourceManager.GetString("無法取得登入者資訊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得要處理資料的參數 的當地語系化字串。
        /// </summary>
        internal static string 無法取得要處理資料的參數 {
            get {
                return ResourceManager.GetString("無法取得要處理資料的參數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        internal static string 狀態 {
            get {
                return ResourceManager.GetString("狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 班別代碼 的當地語系化字串。
        /// </summary>
        internal static string 班別代碼 {
            get {
                return ResourceManager.GetString("班別代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 班別名稱 的當地語系化字串。
        /// </summary>
        internal static string 班別名稱 {
            get {
                return ResourceManager.GetString("班別名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生日 的當地語系化字串。
        /// </summary>
        internal static string 生日 {
            get {
                return ResourceManager.GetString("生日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生　　　日 的當地語系化字串。
        /// </summary>
        internal static string 生日_Mobile {
            get {
                return ResourceManager.GetString("生日_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生 ODS 媒體檔 的當地語系化字串。
        /// </summary>
        internal static string 產生媒體檔ODS {
            get {
                return ResourceManager.GetString("產生媒體檔ODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生 XLS 媒體檔 的當地語系化字串。
        /// </summary>
        internal static string 產生媒體檔XLS {
            get {
                return ResourceManager.GetString("產生媒體檔XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生 ODS 檔案 的當地語系化字串。
        /// </summary>
        internal static string 產生檔案ODS {
            get {
                return ResourceManager.GetString("產生檔案ODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生 XLS 檔案 的當地語系化字串。
        /// </summary>
        internal static string 產生檔案XLS {
            get {
                return ResourceManager.GetString("產生檔案XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生 ODS 清冊 的當地語系化字串。
        /// </summary>
        internal static string 產生清冊ODS {
            get {
                return ResourceManager.GetString("產生清冊ODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生 XLS 清冊 的當地語系化字串。
        /// </summary>
        internal static string 產生清冊XLS {
            get {
                return ResourceManager.GetString("產生清冊XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 科系代碼 的當地語系化字串。
        /// </summary>
        internal static string 科系代碼 {
            get {
                return ResourceManager.GetString("科系代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 科系名稱 的當地語系化字串。
        /// </summary>
        internal static string 科系名稱 {
            get {
                return ResourceManager.GetString("科系名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網站導覽 的當地語系化字串。
        /// </summary>
        internal static string 網站導覽 {
            get {
                return ResourceManager.GetString("網站導覽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網頁參數不正確 的當地語系化字串。
        /// </summary>
        internal static string 網頁參數不正確 {
            get {
                return ResourceManager.GetString("網頁參數不正確", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總學分數 的當地語系化字串。
        /// </summary>
        internal static string 總學分數 {
            get {
                return ResourceManager.GetString("總學分數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳款 的當地語系化字串。
        /// </summary>
        internal static string 繳款 {
            get {
                return ResourceManager.GetString("繳款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費/銷帳資料 的當地語系化字串。
        /// </summary>
        internal static string 繳費_銷帳資料 {
            get {
                return ResourceManager.GetString("繳費/銷帳資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費單 的當地語系化字串。
        /// </summary>
        internal static string 繳費單 {
            get {
                return ResourceManager.GetString("繳費單", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費方式 的當地語系化字串。
        /// </summary>
        internal static string 繳費方式 {
            get {
                return ResourceManager.GetString("繳費方式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費期限 的當地語系化字串。
        /// </summary>
        internal static string 繳費期限 {
            get {
                return ResourceManager.GetString("繳費期限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費狀態查詢 的當地語系化字串。
        /// </summary>
        internal static string 繳費狀態查詢 {
            get {
                return ResourceManager.GetString("繳費狀態查詢", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費管道 的當地語系化字串。
        /// </summary>
        internal static string 繳費管道 {
            get {
                return ResourceManager.GetString("繳費管道", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費金額 的當地語系化字串。
        /// </summary>
        internal static string 繳費金額 {
            get {
                return ResourceManager.GetString("繳費金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費金額合計 的當地語系化字串。
        /// </summary>
        internal static string 繳費金額合計 {
            get {
                return ResourceManager.GetString("繳費金額合計", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繳費/銷帳資料 的當地語系化字串。
        /// </summary>
        internal static string 繳費銷帳資料 {
            get {
                return ResourceManager.GetString("繳費銷帳資料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 缺少網頁參數 的當地語系化字串。
        /// </summary>
        internal static string 缺少網頁參數 {
            get {
                return ResourceManager.GetString("缺少網頁參數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 英文版 的當地語系化字串。
        /// </summary>
        internal static string 英文版 {
            get {
                return ResourceManager.GetString("英文版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 虛擬帳號 的當地語系化字串。
        /// </summary>
        internal static string 虛擬帳號 {
            get {
                return ResourceManager.GetString("虛擬帳號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複製 的當地語系化字串。
        /// </summary>
        internal static string 複製 {
            get {
                return ResourceManager.GetString("複製", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 要退的學分數 的當地語系化字串。
        /// </summary>
        internal static string 要退的學分數 {
            get {
                return ResourceManager.GetString("要退的學分數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 要退金額 的當地語系化字串。
        /// </summary>
        internal static string 要退金額 {
            get {
                return ResourceManager.GetString("要退金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 計算後的可貸金額 的當地語系化字串。
        /// </summary>
        internal static string 計算後的可貸金額 {
            get {
                return ResourceManager.GetString("計算後的可貸金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 說明 的當地語系化字串。
        /// </summary>
        internal static string 說明 {
            get {
                return ResourceManager.GetString("說明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 課程代碼 的當地語系化字串。
        /// </summary>
        internal static string 課程代碼 {
            get {
                return ResourceManager.GetString("課程代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 課程名稱 的當地語系化字串。
        /// </summary>
        internal static string 課程名稱 {
            get {
                return ResourceManager.GetString("課程名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 課程學分數 的當地語系化字串。
        /// </summary>
        internal static string 課程學分數 {
            get {
                return ResourceManager.GetString("課程學分數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入學號 的當地語系化字串。
        /// </summary>
        internal static string 請輸入學號 {
            get {
                return ResourceManager.GetString("請輸入學號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入密碼 的當地語系化字串。
        /// </summary>
        internal static string 請輸入密碼 {
            get {
                return ResourceManager.GetString("請輸入密碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇學校 的當地語系化字串。
        /// </summary>
        internal static string 請選擇學校 {
            get {
                return ResourceManager.GetString("請選擇學校", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 費用別 的當地語系化字串。
        /// </summary>
        internal static string 費用別 {
            get {
                return ResourceManager.GetString("費用別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料建立日期 的當地語系化字串。
        /// </summary>
        internal static string 資料建立日期 {
            get {
                return ResourceManager.GetString("資料建立日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份證字號 的當地語系化字串。
        /// </summary>
        internal static string 身份證字號_Mobile {
            get {
                return ResourceManager.GetString("身份證字號_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記01代碼 的當地語系化字串。
        /// </summary>
        internal static string 身分註記01代碼 {
            get {
                return ResourceManager.GetString("身分註記01代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記01名稱 的當地語系化字串。
        /// </summary>
        internal static string 身分註記01名稱 {
            get {
                return ResourceManager.GetString("身分註記01名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記02代碼 的當地語系化字串。
        /// </summary>
        internal static string 身分註記02代碼 {
            get {
                return ResourceManager.GetString("身分註記02代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記02名稱 的當地語系化字串。
        /// </summary>
        internal static string 身分註記02名稱 {
            get {
                return ResourceManager.GetString("身分註記02名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記03代碼 的當地語系化字串。
        /// </summary>
        internal static string 身分註記03代碼 {
            get {
                return ResourceManager.GetString("身分註記03代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記03名稱 的當地語系化字串。
        /// </summary>
        internal static string 身分註記03名稱 {
            get {
                return ResourceManager.GetString("身分註記03名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記04代碼 的當地語系化字串。
        /// </summary>
        internal static string 身分註記04代碼 {
            get {
                return ResourceManager.GetString("身分註記04代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記04名稱 的當地語系化字串。
        /// </summary>
        internal static string 身分註記04名稱 {
            get {
                return ResourceManager.GetString("身分註記04名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記05代碼 的當地語系化字串。
        /// </summary>
        internal static string 身分註記05代碼 {
            get {
                return ResourceManager.GetString("身分註記05代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記05名稱 的當地語系化字串。
        /// </summary>
        internal static string 身分註記05名稱 {
            get {
                return ResourceManager.GetString("身分註記05名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記06代碼 的當地語系化字串。
        /// </summary>
        internal static string 身分註記06代碼 {
            get {
                return ResourceManager.GetString("身分註記06代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分註記06名稱 的當地語系化字串。
        /// </summary>
        internal static string 身分註記06名稱 {
            get {
                return ResourceManager.GetString("身分註記06名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身分證字號 的當地語系化字串。
        /// </summary>
        internal static string 身分證字號 {
            get {
                return ResourceManager.GetString("身分證字號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入工作表名稱 的當地語系化字串。
        /// </summary>
        internal static string 輸入工作表名稱 {
            get {
                return ResourceManager.GetString("輸入工作表名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 退費方式標準代碼 的當地語系化字串。
        /// </summary>
        internal static string 退費方式標準代碼 {
            get {
                return ResourceManager.GetString("退費方式標準代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 退費金額 的當地語系化字串。
        /// </summary>
        internal static string 退費金額 {
            get {
                return ResourceManager.GetString("退費金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇上傳對照檔 的當地語系化字串。
        /// </summary>
        internal static string 選擇上傳對照檔 {
            get {
                return ResourceManager.GetString("選擇上傳對照檔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇上傳檔案所在位置 的當地語系化字串。
        /// </summary>
        internal static string 選擇上傳檔案所在位置 {
            get {
                return ResourceManager.GetString("選擇上傳檔案所在位置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇上傳檔案類型 的當地語系化字串。
        /// </summary>
        internal static string 選擇上傳檔案類型 {
            get {
                return ResourceManager.GetString("選擇上傳檔案類型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 部別 的當地語系化字串。
        /// </summary>
        internal static string 部別 {
            get {
                return ResourceManager.GetString("部別", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵遞區號 的當地語系化字串。
        /// </summary>
        internal static string 郵遞區號 {
            get {
                return ResourceManager.GetString("郵遞區號", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重填 的當地語系化字串。
        /// </summary>
        internal static string 重填 {
            get {
                return ResourceManager.GetString("重填", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銷帳狀態 的當地語系化字串。
        /// </summary>
        internal static string 銷帳狀態 {
            get {
                return ResourceManager.GetString("銷帳狀態", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 院別代碼 的當地語系化字串。
        /// </summary>
        internal static string 院別代碼 {
            get {
                return ResourceManager.GetString("院別代碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 院別名稱 的當地語系化字串。
        /// </summary>
        internal static string 院別名稱 {
            get {
                return ResourceManager.GetString("院別名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離開 的當地語系化字串。
        /// </summary>
        internal static string 離開 {
            get {
                return ResourceManager.GetString("離開", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件 的當地語系化字串。
        /// </summary>
        internal static string 電子郵件 {
            get {
                return ResourceManager.GetString("電子郵件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        internal static string 電話 {
            get {
                return ResourceManager.GetString("電話", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 項 的當地語系化字串。
        /// </summary>
        internal static string 項 {
            get {
                return ResourceManager.GetString("項", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證碼錯誤，請重新輸入 的當地語系化字串。
        /// </summary>
        internal static string 驗證碼錯誤請重新輸入 {
            get {
                return ResourceManager.GetString("驗證碼錯誤請重新輸入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點上圖可更新驗證碼 的當地語系化字串。
        /// </summary>
        internal static string 點上圖可更新驗證碼 {
            get {
                return ResourceManager.GetString("點上圖可更新驗證碼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點上圖可更新驗證碼 的當地語系化字串。
        /// </summary>
        internal static string 點上圖可更新驗證碼_Mobile {
            get {
                return ResourceManager.GetString("點上圖可更新驗證碼_Mobile", resourceCulture);
            }
        }
    }
}
