//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboundChangeKey.FiscService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FiscService.FiscServiceSoap")]
    public interface FiscServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  checkCode 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InboundChangeKey", ReplyAction="*")]
        InboundChangeKey.FiscService.InboundChangeKeyResponse InboundChangeKey(InboundChangeKey.FiscService.InboundChangeKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InboundChangeKey", ReplyAction="*")]
        System.Threading.Tasks.Task<InboundChangeKey.FiscService.InboundChangeKeyResponse> InboundChangeKeyAsync(InboundChangeKey.FiscService.InboundChangeKeyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InboundChangeKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InboundChangeKey", Namespace="http://tempuri.org/", Order=0)]
        public InboundChangeKey.FiscService.InboundChangeKeyRequestBody Body;
        
        public InboundChangeKeyRequest() {
        }
        
        public InboundChangeKeyRequest(InboundChangeKey.FiscService.InboundChangeKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InboundChangeKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int jobNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string checkCode;
        
        public InboundChangeKeyRequestBody() {
        }
        
        public InboundChangeKeyRequestBody(int jobNo, string checkCode) {
            this.jobNo = jobNo;
            this.checkCode = checkCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InboundChangeKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InboundChangeKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public InboundChangeKey.FiscService.InboundChangeKeyResponseBody Body;
        
        public InboundChangeKeyResponse() {
        }
        
        public InboundChangeKeyResponse(InboundChangeKey.FiscService.InboundChangeKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InboundChangeKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InboundChangeKeyResult;
        
        public InboundChangeKeyResponseBody() {
        }
        
        public InboundChangeKeyResponseBody(string InboundChangeKeyResult) {
            this.InboundChangeKeyResult = InboundChangeKeyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiscServiceSoapChannel : InboundChangeKey.FiscService.FiscServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiscServiceSoapClient : System.ServiceModel.ClientBase<InboundChangeKey.FiscService.FiscServiceSoap>, InboundChangeKey.FiscService.FiscServiceSoap {
        
        public FiscServiceSoapClient() {
        }
        
        public FiscServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiscServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiscServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiscServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InboundChangeKey.FiscService.InboundChangeKeyResponse InboundChangeKey.FiscService.FiscServiceSoap.InboundChangeKey(InboundChangeKey.FiscService.InboundChangeKeyRequest request) {
            return base.Channel.InboundChangeKey(request);
        }
        
        public string InboundChangeKey(int jobNo, string checkCode) {
            InboundChangeKey.FiscService.InboundChangeKeyRequest inValue = new InboundChangeKey.FiscService.InboundChangeKeyRequest();
            inValue.Body = new InboundChangeKey.FiscService.InboundChangeKeyRequestBody();
            inValue.Body.jobNo = jobNo;
            inValue.Body.checkCode = checkCode;
            InboundChangeKey.FiscService.InboundChangeKeyResponse retVal = ((InboundChangeKey.FiscService.FiscServiceSoap)(this)).InboundChangeKey(inValue);
            return retVal.Body.InboundChangeKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InboundChangeKey.FiscService.InboundChangeKeyResponse> InboundChangeKey.FiscService.FiscServiceSoap.InboundChangeKeyAsync(InboundChangeKey.FiscService.InboundChangeKeyRequest request) {
            return base.Channel.InboundChangeKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<InboundChangeKey.FiscService.InboundChangeKeyResponse> InboundChangeKeyAsync(int jobNo, string checkCode) {
            InboundChangeKey.FiscService.InboundChangeKeyRequest inValue = new InboundChangeKey.FiscService.InboundChangeKeyRequest();
            inValue.Body = new InboundChangeKey.FiscService.InboundChangeKeyRequestBody();
            inValue.Body.jobNo = jobNo;
            inValue.Body.checkCode = checkCode;
            return ((InboundChangeKey.FiscService.FiscServiceSoap)(this)).InboundChangeKeyAsync(inValue);
        }
    }
}
